services:
  - type: web
    name: spa-news-monitor
    env: python
    buildCommand: |
      # Install Chrome dependencies
      apt-get update
      apt-get install -y wget gnupg
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_USERNAME
        value: asedalnajar198@gmail.com
      - key: EMAIL_PASSWORD
        value: vwnjbeyxmeqvrgig
      - key: EMAIL_FROM
        value: asedalnajar198@gmail.com
      - key: EMAIL_TO
        value: gotomoneybox2020@gmail.com
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: TARGET_URL
        value: https://www.spa.gov.sa/en/news/latest-news?page=1
      - key: OPENAI_MODEL
        value: gpt-4.1
      - key: CHECK_INTERVAL_MINUTES
        value: 60
    plan: starter